export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_CLEANUP = 'LOGIN_CLEANUP';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_CLEANUP = 'SIGNUP_CLEANUP';

export const GET_RESTAURANTS_START = 'GET_RESTAURANTS_START';
export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';
export const GET_RESTAURANTS_FAIL = 'GET_RESTAURANTS_FAIL';
export const GET_RESTAURANTS_CLEANUP = 'GET_RESTAURANTS_CLEANUP';

export const GET_CUISINES_START = 'GET_CUISINES_START';
export const GET_CUISINES_SUCCESS = 'GET_CUISINES_SUCCESS';
export const GET_CUISINES_FAIL = 'GET_CUISINES_FAIL';
export const GET_CUISINES_CLEANUP = 'GET_CUISINES_CLEANUP';

export const GET_LOCATIONS_START = 'GET_LOCATIONS_START';
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAIL = 'GET_LOCATIONS_FAIL';
export const GET_LOCATIONS_CLEANUP = 'GET_LOCATIONS_CLEANUP';

export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const GET_PROFILE_CLEANUP = 'GET_PROFILE_CLEANUP';